# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hybrid-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hybrid-ios

end

# Import shared flutter framework
flutter_application_path = '../fluttershared/'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
